aws_region     = "ap-south-1"
project        = "devops-task"
docker_repo    = "saravana2002/devops-task"
container_port = 3000
health_path    = "/"
cpu            = 256
memory         = 512
image_tag      = "18"          # this will be overridden from Jenkins BUILD_NUMBER
min_capacity   = 1
max_capacity   = 3
